version: "3.8"

services:
  api:
    image: cosmtrek/air
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"
    working_dir: /project
    volumes:
      - ./:/project/
    ports:
      - "3001:8081"

    environment:
      - PORT=8081
